# Generated by Django 5.0.14 on 2025-12-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='If Active, no new transactions can be created via API.')),
                ('global_deposit_limit', models.DecimalField(decimal_places=2, default=100000.0, help_text='Global limit for daily deposits.', max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('MANUAL', 'Manual Adjustment')], max_length=20),
        ),
    ]
