# Generated by Django 6.0 on 2025-12-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_systemconfig_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_ban',
            field=models.CharField(blank=True, help_text='Target IBAN for withdrawals', max_length=34, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='target_name',
            field=models.CharField(blank=True, help_text='Target Account Holder Name', max_length=255, null=True),
        ),
    ]
