# Generated by Django 6.0 on 2025-12-23 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_target_ban_transaction_target_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='target_ban',
            new_name='target_iban',
        ),
    ]
