# Generated by Django 6.0 on 2025-12-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_rename_target_ban_transaction_target_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Admin notes for this transaction', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('MANUAL_CREDIT', 'Manual Credit (+)'), ('MANUAL_DEBIT', 'Manual Debit (-)'), ('MANUAL', 'Manual (Legacy)')], max_length=20),
        ),
    ]
