# Generated by Django 6.0 on 2025-12-23 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0005_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'İşlem', 'verbose_name_plural': 'İşlemler'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='max_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, help_text='Maximum deposit amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='min_deposit_limit',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum deposit amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.bankaccount', verbose_name='Banka Hesabı'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, help_text='Admin notes for this transaction', null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='external_user_id',
            field=models.CharField(help_text='User ID from external system', max_length=100, verbose_name='Harici Kullanıcı ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='İşlem Tarihi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Başlatıldı'), ('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.subdealerprofile', verbose_name='Alt Bayi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_iban',
            field=models.CharField(blank=True, help_text='Target IBAN for withdrawals', max_length=34, null=True, verbose_name='Hedef IBAN'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_name',
            field=models.CharField(blank=True, help_text='Target Account Holder Name', max_length=255, null=True, verbose_name='Hedef Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Yatırım'), ('WITHDRAW', 'Çekim'), ('MANUAL_CREDIT', 'Manuel Ekleme (+)'), ('MANUAL_DEBIT', 'Manuel Kesinti (-)'), ('MANUAL', 'Manuel (Eski)')], max_length=20, verbose_name='İşlem Tipi'),
        ),
    ]
