# Generated by Django 6.0 on 2025-12-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transaction_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Komisyon Tutarı'),
        ),
    ]
