# Generated by Django 6.0 on 2025-12-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_transaction_commission_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gönderen Adı Soyadı'),
        ),
    ]
