# Generated by Django 6.0 on 2025-12-24 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('finance', '0009_transaction_sender_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Başlatıldı'), ('WAITING_ASSIGNMENT', 'Atama Bekliyor'), ('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sub_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.subdealerprofile', verbose_name='Alt Bayi'),
        ),
    ]
