# Generated by Django 6.0 on 2025-12-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_transaction_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('WAITING_ASSIGNMENT', 'Atama Bekliyor'), ('PENDING', 'Bekliyor'), ('APPROVED', 'Onaylandı'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20, verbose_name='Durum'),
        ),
    ]
