# Generated by Django 6.0 on 2025-12-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_transaction_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='allow_withdrawals',
            field=models.BooleanField(default=True, help_text='Global switch to enable/disable withdrawals.'),
        ),
    ]
