# Generated by Django 6.0 on 2025-12-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_systemconfig_allow_withdrawals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IBAN', 'IBAN'), ('IP', 'IP Address'), ('USER_ID', 'User ID')], max_length=20)),
                ('value', models.CharField(help_text='The blocked value (e.g., IBAN, IP, or User ID)', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Reason for blocking', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
