# Generated by Django 6.0 on 2025-12-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='processed_by_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to='finance.bankaccount', verbose_name='Ödenen Banka'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Dekont'),
        ),
    ]
