# Generated by Django 6.0 on 2025-12-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_transaction_processed_by_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('TAKVIYE', 'Kasa Takviyesi'), ('TESLIMAT', 'Elden Teslimat'), ('MASRAF', 'Operasyonel Masraf'), ('DUZELTME', 'Hatalı İşlem Düzeltme'), ('DIGER', 'Diğer')], max_length=20, null=True, verbose_name='Kategori'),
        ),
    ]
