# Generated by Django 6.0 on 2025-12-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subdealerprofile_options_and_more'),
        ('finance', '0017_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.apiclient', verbose_name='API İstemcisi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='callback_url',
            field=models.URLField(blank=True, help_text='Notification URL for status updates', max_length=500, null=True, verbose_name='Callback URL'),
        ),
    ]
