# Generated by Django 6.0 on 2026-01-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_transaction_api_client_transaction_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='Transaction ID from external system', max_length=100, null=True, verbose_name='Harici İşlem ID'),
        ),
    ]
