# Generated by Django 6.0 on 2025-12-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('api_key', models.CharField(blank=True, max_length=64, unique=True, verbose_name='API Key')),
                ('allowed_ips', models.TextField(default='127.0.0.1', help_text='Virgülle ayrılmış IP listesi', verbose_name="İzinli IP'ler")),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API İstemcisi',
                'verbose_name_plural': 'API İstemcileri',
            },
        ),
    ]
