# Generated by Django 6.0 on 2025-12-24 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apiclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='İşlem')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hedef Tablo')),
                ('target_object_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hedef ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='Cihaz Bilgisi')),
                ('details', models.JSONField(default=dict, verbose_name='Detaylar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
    ]
