# Generated by Django 6.0 on 2025-12-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdealerprofile',
            name='can_edit_amounts',
            field=models.BooleanField(default=False, verbose_name='Miktar Düzenleyebilir mi?'),
        ),
    ]
