# Generated by Django 6.0 on 2025-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subdealerprofile_can_edit_amounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdealerprofile',
            options={'verbose_name': 'Alt Bayi', 'verbose_name_plural': 'Alt Bayiler (Sahalar)'},
        ),
        migrations.AddField(
            model_name='apiclient',
            name='webhook_secret',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SUBDEALER', 'Alt Bayi')], default='SUBDEALER', max_length=20),
        ),
    ]
