# Generated by Django 6.0 on 2025-12-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subdealerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdealerprofile',
            name='can_make_withdraw',
            field=models.BooleanField(default=True, verbose_name='Çekim Yapabilir mi?'),
        ),
        migrations.AddField(
            model_name='subdealerprofile',
            name='can_receive_deposit',
            field=models.BooleanField(default=True, verbose_name='Yatırım Alabilir mi?'),
        ),
        migrations.AddField(
            model_name='subdealerprofile',
            name='deposit_commission_rate',
            field=models.FloatField(default=0.0, verbose_name='Yatırım Komisyonu (%)'),
        ),
        migrations.AddField(
            model_name='subdealerprofile',
            name='withdraw_commission_rate',
            field=models.FloatField(default=0.0, verbose_name='Çekim Komisyonu (%)'),
        ),
    ]
